upd: implement new update and migration flow

diff --git a/bin/scripts/omarell-update b/bin/scripts/omarell-update
--- a/bin/scripts/omarell-update
+++ b/bin/scripts/omarell-update
@@ -1,27 +1,16 @@
 #!/bin/bash
 
-cd $HOME/.local/share/omarell
+# Exit immediately if a command exits with a non-zero status
+set -e
 
-if [[ $1 == "all" ]]; then
-  # Run all migrations since the root commit
-  migration_starting_point=$(git log --max-parents=0 --first-parent --format="%H")
-else
-  # Remember the commit we're at before upgrading in order to only run new migrations
-  migration_starting_point=$(git log -1 --format=%H)
-fi
+# Show logo
+clear
+cat ~/.local/share/omarell/logo.txt
 
 # Get the latest while trying to preserve any modifications
-git pull --autostash
-git diff --check || git reset --merge
+omarell_path=~/.local/share/omarell
+git -C $omarell_path pull --autostash
+git -C $omarell_path diff --check || git -C $omarell_path reset --merge
 
-# Run any pending migrations
-for file in $(git diff --name-only --diff-filter=A $migration_starting_point.. migrations/*.sh); do
-  filename=$(basename "$file")
-  migrate_at="${filename%.sh}"
-
-  echo -e "\e[32m\nRunning migration ($migrate_at)\e[0m"
-  source $file
-done
-
-# Back to where we came from
-cd - >/dev/null
+# Run migrations
+"$HOME/.local/share/omarell/bin/omarell-migrate"
